# Generated by Django 4.2.25 on 2025-11-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AddField(
            model_name='timeslot',
            name='block_reason',
            field=models.TextField(blank=True, verbose_name='Причина блокировки'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда заблокировано'),
        ),
    ]
